version: '3.0'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongovolume:/data/db'
    restart: unless-stopped
    container_name: mongo
  rabbit:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_VHOST=emerge
    volumes:
      - 'rmqvolume:/var/lib/rabbitmq'
    restart: unless-stopped
    container_name: rmq
volumes:
  rmqvolume: null
  mongovolume: null